<a href="https://colab.research.google.com/github/LuisPeMoraRod/AI-Laboratories/blob/main/Lab5_MatrixProgrammed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:

# import libraries
import torch


### Ejercicio 1
Implemente la función *calcularTrazaMatriz*, la cual calcula la traza de una matriz usando únicamente operaciones básicas en Pytorch (multiplicación, multiplicación por elemento, matriz identidad, etc), prescindiendo de estructuras de repetición como el for el while. (10 pts) 


### Ejercicio 2
Desarrolle la tranpuesta de una matriz. (10 pts)

In [49]:
import torch

def transpuesta(mat):

    # Utilizamos la función view() para intercambiar las dimensiones del tensor
    transpuesta_mat = mat.permute(1, 0)
    
    return transpuesta_mat


# Creamos una matriz de ejemplo
matriz = torch.tensor([[1, 2, 3], [4, 5, 6],[7, 8, 9]])


transpuesta_mat = transpuesta(matriz)


print("------------ Resultados ----------------")
print("Matriz Original")
print(matriz)
print("Matriz Transpuesta")
print(transpuesta_mat)





------------ Resultados ----------------
Matriz Original
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Matriz Transpuesta
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


### Ejercicio 3
Desarrolle la matriz adjunta de una matriz (10 pts)

In [50]:
class Adj:
  # auxiliar variables used to loop through the Tensor
  i = 0
  j = 0
  def __init__(self, M: torch.Tensor):
    self.M = M
    self.rows = len(M)
    self.col = len(M[0])
    self.ones = torch.ones(self.rows, self.col)
    self.adj = self.get_adj_matrix()

  def __str__(self):
    return str(self.adj)

  def get_minor(self, i : int, j : int):
      """
      Return the minor matrix in relation to indexes i and j
      """
      M = torch.cat((self.M[:i],self.M[i+1:])) # delete row i
      M = torch.transpose(M, 0, 1)
      M = torch.cat((M[:j], M[j+1:])) # delete column j
      M = torch.transpose(M, 0, 1)
      return M

  def get_cofactor(self, element) -> int:
    """
    Returns the cofactor for a specific element in the matrix
    """
    minor = self.get_minor(self.i, self.j)
    determinant = torch.det(minor)
    result = (-element)**(self.i+self.j)*determinant #computes cofactor

    #update indexes
    if (self.j + 1 == len(self.M[0])):
      self.i+=1
      self.j = 0
    else:
      self.j+=1

    return result

  def get_cofactors_matrix(self) -> torch.Tensor:
    return self.ones.apply_(self.get_cofactor) #applies get_factor method to every element in ones matrix

  def get_adj_matrix(self) -> torch.Tensor:
    cofactor_matrix = self.get_cofactors_matrix()
    return torch.transpose(cofactor_matrix, 0, 1)

M = [[7, 5, 3, 4], [2, 3, 6, 4], [6, 10, 9, 4], [1, 2, 3, 4]]
M = torch.tensor(M, dtype=torch.float64)
print(f'Original matrix:\n{M}')
adj_matrix = Adj(M)
print(f'\n\nAdjugate matrix:\n{adj_matrix}')


Original matrix:
tensor([[ 7.,  5.,  3.,  4.],
        [ 2.,  3.,  6.,  4.],
        [ 6., 10.,  9.,  4.],
        [ 1.,  2.,  3.,  4.]], dtype=torch.float64)


Adjugate matrix:
tensor([[ -72.,  -72.,   36.,  108.],
        [  36.,  144.,  -72., -108.],
        [  12., -132.,   12.,  108.],
        [  -9.,   45.,   18., -135.]])


### Ejercicio 4
Desarrolle la inversa de una matriz. Debe validar si es invertible o no. (20 pts)

In [54]:

# Metodo para determinar la inversa de una matriz

def matriz_inversa(matrix):
  
  # Cálculo del determinante
  determinante = torch.det(matrix)

  # Verificación de si tiene inversa
  if  determinante == 0:
    return "La matriz no tiene inversa"

  # Cálculo de la inversa usando la fórmula general
  m_transpuesta = transpuesta(matrix)
  m_adj = Adj(m_transpuesta)
  m_inversa = m_adj.adj/determinante

  return m_inversa

matriz = torch.tensor([[2, -2, 2], [2, 1, 0],[3, -2, 2]])
matriz_tensor = torch.tensor(matriz, dtype=torch.float64)
a = Adj(matriz_tensor)
mat_inversa = matriz_inversa(matriz_tensor)
print("------------ Método programado ----------------")
print("Matriz Original")
print(matriz)
print("Matriz Inversa")
print(mat_inversa)


------------ Método programado ----------------
Matriz Original
tensor([[ 2, -2,  2],
        [ 2,  1,  0],
        [ 3, -2,  2]])
Matriz Inversa
tensor([[-1.0000,  2.0000,  3.5000],
        [-0.0000,  1.0000,  1.0000],
        [ 1.0000, -2.0000, -3.0000]])


<ipython-input-54-485ffe889663>:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  matriz_tensor = torch.tensor(matriz, dtype=torch.float64)


### Ejercicio 5
La Matriz de covarianza. (50 pts) 