<a href="https://colab.research.google.com/github/LuisPeMoraRod/AI-Laboratories/blob/main/Lab5_MatrixProgrammed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

# import libraries
import torch


### Ejercicio 1
Implemente la función *calcularTrazaMatriz*, la cual calcula la traza de una matriz usando únicamente operaciones básicas en Pytorch (multiplicación, multiplicación por elemento, matriz identidad, etc), prescindiendo de estructuras de repetición como el for el while. (10 pts) 


### Ejercicio 2
Desarrolle la tranpuesta de una matriz. (10 pts)

In [ ]:
import numpy as np


# Método que permite obtener la matriz transpuesta.


def transpose_matrix(matrix):

    # Obtener el numero de filas y columnas de la matriz
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    # Creamos una matriz de ceros invertida
    transpose = [[0 for j in range(num_rows)] for i in range(num_cols)]

    # iteramos cada elemento de la matriz junto con la creada
    for i in range(num_rows):
        for j in range(num_cols):
            # Agregamos los datos correspondientes a la matriz tranpuesta
            transpose[j][i] = matrix[i][j]

    return transpose

# Método que permite imprimir las matrices.

def printMatrix(matrix):
  for row in matrix:
    print(row)


matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print("------------ Método programado ----------------")
print("Matriz Original")
printMatrix(matriz)
transpose = transpose_matrix(matriz)
print("Matriz Transpuesta")
printMatrix(transpose)

print("------------ Con librería ----------------")

print("Matriz Transpuesta")

npmatriz = np.array(matriz).transpose()
printMatrix(npmatriz)

------------ Método programado ----------------
Matriz Original
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Matriz Transpuesta
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]
------------ Con librería ----------------
Matriz Transpuesta
[1 4 7]
[2 5 8]
[3 6 9]


### Ejercicio 3
Desarrolle la matriz adjunta de una matriz (10 pts)

In [61]:
def get_minor(M : torch.Tensor, i : int, j : int):
    M = torch.cat((M[:i],M[i+1:])) # delete row i
    M = torch.transpose(M, 0, 1)#transpose matrix to tranform columns into rows
    M = torch.cat((M[:j], M[j+1:]))
    M = torch.transpose(M, 0, 1)
    return M

def get_cofactor(element) -> int:
  global i,j,M
  minor = get_minor(M, i, j)
  determinant = torch.det(minor)
  print(M)
  print(f'{element}\t{determinant}')
  result = (-1)**(i+j)*determinant
  if (j + 1 == len(M[0])):
    i+=1
    j = 0
  else:
    j+=1
  return result

def get_cofactor_matrix(M: torch.Tensor) -> torch.Tensor:
  return M.apply_(get_cofactor)

def get_adj_matrix(M: torch.Tensor) -> torch.Tensor:
  cofactor_matrix = get_cofactor_matrix(M)
  return torch.transpose(cofactor_matrix, 0, 1)

i = 0
j = 0
M = [[7, 5, 3], [2, 3, 6], [6, 10, 9]]
M = torch.tensor(M, dtype=torch.float64)
m = get_minor(M, 1, 0)
print(M)
#print(m)
#print(torch.det(m))
print(get_adj_matrix(M))


tensor([[ 7.,  5.,  3.],
        [ 2.,  3.,  6.],
        [ 6., 10.,  9.]], dtype=torch.float64)
tensor([[ 7.,  5.,  3.],
        [ 2.,  3.,  6.],
        [ 6., 10.,  9.]], dtype=torch.float64)
7.0	-33.0
tensor([[-33.,   5.,   3.],
        [  2.,   3.,   6.],
        [  6.,  10.,   9.]], dtype=torch.float64)
5.0	-18.0
tensor([[-33.,  18.,   3.],
        [  2.,   3.,   6.],
        [  6.,  10.,   9.]], dtype=torch.float64)
3.0	1.9999999999999982
tensor([[-33.0000,  18.0000,   2.0000],
        [  2.0000,   3.0000,   6.0000],
        [  6.0000,  10.0000,   9.0000]], dtype=torch.float64)
2.0	142.0
tensor([[ -33.0000,   18.0000,    2.0000],
        [-142.0000,    3.0000,    6.0000],
        [   6.0000,   10.0000,    9.0000]], dtype=torch.float64)
3.0	-309.0
tensor([[ -33.0000,   18.0000,    2.0000],
        [-142.0000, -309.0000,    6.0000],
        [   6.0000,   10.0000,    9.0000]], dtype=torch.float64)
6.0	-438.0
tensor([[ -33.0000,   18.0000,    2.0000],
        [-142.0000, -309.0000,  

### Ejercicio 4
Desarrolle la inversa de una matriz. Debe validar si es invertible o no. (20 pts)

In [ ]:
import numpy as np

def inverse_matrix(matrix):
 return [[2, -2, 2], [2, 1, 0], [3, -2, 2]]

matriz = [[2, -2, 2], [2, 1, 0], [3, -2, 2]]

print("------------ Método programado ----------------")
print("Matriz Original")
printMatrix(matriz)
inverse = inverse_matrix(matriz)
print("Matriz Inversa")
printMatrix(inverse)

print("------------ Con librería ----------------")

print("Matriz Inversa")

npmatriz = np.array(matriz)

npmatriz_inv = np.linalg.inv(npmatriz)

printMatrix(npmatriz_inv)

------------ Método programado ----------------
Matriz Original
[2, -2, 2]
[2, 1, 0]
[3, -2, 2]
Matriz Inversa
[2, -2, 2]
[2, 1, 0]
[3, -2, 2]
------------ Con librería ----------------
Matriz Inversa
[-1.00000000e+00  1.48029737e-16  1.00000000e+00]
[ 2.  1. -2.]
[ 3.5  1.  -3. ]


### Ejercicio 5
La Matriz de covarianza. (50 pts) 